# Generated by Django 5.1.7 on 2025-03-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artistprofile_first_name_artistprofile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='first_name',
            new_name='artist_name',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='last_name',
        ),
    ]
