# Generated by Django 5.1.7 on 2025-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_first_name_artistprofile_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='no_of_albums_released',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
